### ISSUE TITLE
Can \equiv be made less blurred?

### ISSUE THREAD

**Issue by freemaths** [Khan/KaTeX#1321]
\equiv renders with a clear central line but blurred upper and lower. Can these be made clearer?
Identities are important so I use the \equiv symbol lots.
![image](https://user-images.githubusercontent.com/5670897/40159271-65e39114-59a0-11e8-8d62-021a68695b59.png)

**Comment by ronkok** [comment]
@freemaths I'm afraid that the short answer is no.

The long answer is that `\equiv` is rendered by calling a font glyph. It's Unicode U+2261, ≡. In your example, the top and bottom bars of that glyph have happened to fall where they straddles a line between two rows of screen pixels. So the screen renders two gray pixels instead of one dark pixel. There isn't a lot that we can do about that.

As future screens get higher pixel density, the problem will go way.

**Comment by kevinbarabash** [comment]
@freemaths you could try different settings https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth and see which works the best for you.

**Comment by edemaine** [comment]
Closing issue, as I don't see what else we can do, other than possibly thickening the fonts, which is #695.

**Comment by mbourne** [comment]
I'm still trying to understand why font glyphs behave nicely (I mean avoid the fuzzies) in other font families, but not when using KaTex_Main.

In this screen shot, the first example uses KaTeX_Main for \equiv, in the second, I've used a span and styled it as `font-family:serif;font-size:1.11em;color:#555;position:relative;top:2px`. It's not quite wide enough, but avoids the problem on a low-res screen.

![image](https://user-images.githubusercontent.com/7541940/41025982-e204ca64-69a5-11e8-8a71-6e7b140605fa.png)

Presumably adding some text above (so the item "lands" on a real pixel row) should fix it, but my experiments were not so successful.

@kevinbarabash FYI, none of those Mozilla suggestions gave me any joy.

**Comment by ronkok** [comment]
We've complaints about `\equiv` rendering from two different people now, so it's clearly a problem. Is it worth using a symbol built up from `\rule`s?  @mbourne, you could add this to your rendering options:
```
macros: {"\\equiv": "\\mathrel{\\hspace1mu\\mathrlap{\\mathrlap{\\rule[0.65mu]{12mu}{0.72mu}}{\\rule[4.14mu]{12mu}{0.72mu}}}{\\rule[7.63mu]{12mu}{0.72mu}}\\hspace1mu}"}
```
The dimensions inside the square brackets control the height of each rule. What I've written above matches the dimensions of the KaTeX font glyph, but I find that I get a much clearer line if I change `[0.65mu` to `[0.6mu]`.

**Comment by ronkok** [comment]
The rendering option is something that @mbourne can do right away. Is it something we should so in KaTeX master?  Also, we should probably add a `min-height: 1px;` CSS rule to class `.rule`, similar to what we've recently done for fraction lines. That would give more certainty of clear lines.

**Comment by ronkok** [comment]
The drawback is that such a macro pretty thoroughly obfuscates the MathML for `\equiv`.

**Comment by edemaine** [comment]
Reopening for more discussion, though I'm uncomfortable doing things that deviate from Computer Modern fonts much... and it seems difficult to avoid hacks that are too screen-specific to be generally useful.  (On the other hand, `min-height: 1px` on rules seems like a good idea.)  @ronkok Can you write that with a `\stackrel` or something?  Still not sure we want to do that in KaTeX master, but at least it'd be easy for people to define with custom macros...

**Comment by mbourne** [comment]
Once again on readability (since my context is education and way too many students completely miss obvious notations, let alone the subtle ones - especially when using projectors in class rooms). 
Related to the \equiv case, I notice (on a large monitor) the vertical (and sometimes) horizontal bars of plus signs almost disappear. Setting `.mbin{font-weight:bold}` is a crude fix, but helps readability, I feel.
Without: 
![image](https://user-images.githubusercontent.com/7541940/45010165-9f303e00-b03e-11e8-9750-43a6e47debba.png)
With:
![image](https://user-images.githubusercontent.com/7541940/45010172-afe0b400-b03e-11e8-83b1-a89d4e7ce032.png)

Here are 3 accents as produced using my default settings.
![image](https://user-images.githubusercontent.com/7541940/45009880-2e3c5680-b03d-11e8-84d7-f71dd085b90d.png)
When appearing among a lot of other notation (and when it is late at night), I find the hat ^ is a strain to see, the vector arrow is blurred and the dots are a bit small too.
Here they are again with some tweaks:
![image](https://user-images.githubusercontent.com/7541940/45009935-7c515a00-b03d-11e8-8dd6-770b38d6ec4c.png)
For the first and 3rd ones, I bumped up the font size as follows:
`.accent-body{font-size:1.25em}`
For the arrow, I swapped out the default SVG arrow for (what I feel) is a cleaner, simpler arrow, and repositioned it a bit. (You can see these about 2/3 down [this page](https://www.intmath.com/cg5/katex-mathjax-comparison.php)).
Yes, I know this strays from LaTeX rendering, but it does involve less eye strain!

**Comment by ronkok** [comment]
We'll never agree completely on all matters. Sometimes I think that we need a documentation page that describes a set of KaTeX customizations and hacks. Then each website could customize KaTeX per local preferences.  Some people could stick with TeX purity. Others could opt for thicker, bolder renderings.

Maybe that page would be best at a separate domain or maybe we could add a "Customization" page to the Configuring KaTeX section of the docs. Such a page could cover several topics:

#### Customizations to get bolder, thicker renderings.

1. The CSS hacks that @mbourne describes above. 
2. A macro that uses  `\genfrac` to define a version of `\frac` with a thicker fraction line.  
3. `\pmb`
4. After PR #1620 lands, a set of images that could be swapped in via macro for particularly troublesome glyphs such as `\equiv`.

#### Font size

1. The familiar [CSS customization](https://katex.org/docs/font.html).

#### Macros

1. [Long division](https://github.com/Khan/KaTeX/issues/1319#issuecomment-389659229)
2. Pearl's notation for conditional independence, ![](http://quicklatex.com/cache3/14/ql_802e4d6fc5bc3a53e0653cd65aa3fc14_l3.png)

**Comment by mbourne** [comment]
@ronkok I think a Customization page in the configuration section as you mentioned would be great.

(BTW - the link in the final line of your comment has a problem.)
